spring.datasource.url=jdbc:postgresql://localhost:5432/forohub
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
api.security.secret=forohub_clave_super_secreta_123
